apiVersion: v1
data:
  chouette2_db_password: bksyMmpJcFdkM0I5
  chouette2_db_username: Y2hvdWV0dGU=
  devise_secret_key: MDUzM2Q2YzNmOWI0MWJlYTZjMjEzYWFiMTAwMjc0NzdhMjQ5MGI5OGExYzlkYWI1MDdkYTE1ZmI4ZGU4ZjFhZWRiNjIxOGUzMzIzNmVmNjAyYzU0NzUwNjBmYTAzMzUxOGI5ZTVmYmRjMWQ2ZmYxYzQxMzVjNzc1MjkyZWIxZTY=
  secret_key_base: MDUzM2Q2YzNmOWI0MWJlYTZjMjEzYWFiMTAwMjc0NzdhMjQ5MGI5OGExYzlkYWI1MDdkYTE1ZmI4ZGU4ZjFhZWRiNjIxOGUzMzIzNmVmNjAyYzU0NzUwNjBmYTAzMzUxOGI5ZTVmYmRjMWQ2ZmYxYzQxMzVjNzc1MjkyZWIxZTY=
kind: Secret
metadata:
  name: ror-chouette2-secret
  namespace: chouette
type: Opaque
